+ echo Logging output to experiments/logs/faster_rcnn_alt_opt_ZF_.txt.2016-09-08_07-33-16
Logging output to experiments/logs/faster_rcnn_alt_opt_ZF_.txt.2016-09-08_07-33-16
+ ./tools/train_faster_rcnn_alt_opt.py --gpu 1 --net_name ZF --weights data/imagenet_models/ZF.v2.caffemodel --imdb widerface_2016_train --cfg experiments/cfgs/faster_rcnn_alt_opt.yml
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_alt_opt.yml', gpu_id=1, imdb_name='widerface_2016_train', net_name='ZF', pretrained_model='data/imagenet_models/ZF.v2.caffemodel', set_cfgs=None)
Error under config key: TEST
Traceback (most recent call last):
  File "./tools/train_faster_rcnn_alt_opt.py", line 210, in <module>
    cfg_from_file(args.cfg_file)
  File "/disk2/workspace/github/ataraxia/faceX/py-faster-rcnn-zyf/tools/../lib/fast_rcnn/config.py", line 263, in cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/disk2/workspace/github/ataraxia/faceX/py-faster-rcnn-zyf/tools/../lib/fast_rcnn/config.py", line 250, in _merge_a_into_b
    _merge_a_into_b(a[k], b[k])
  File "/disk2/workspace/github/ataraxia/faceX/py-faster-rcnn-zyf/tools/../lib/fast_rcnn/config.py", line 235, in _merge_a_into_b
    raise KeyError('{} is not a valid config key'.format(k))
KeyError: 'MODELS_DIR is not a valid config key'
